apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
  labels:
    where: frontporch
data:
  site-en : |
    :80 {
        root * /var/www/site
        encode zstd gzip
        templates
        file_server browse

        php_fastcgi zendphp:9000 {
            resolve_root_symlink
            dial_timeout  5s
            read_timeout  15m
            write_timeout 30s
        }
    }