apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-docroot
  labels:
    app: adminer
    where: backyard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30M
