apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    where: frontporch
spec:
  selector:
    app: caddy
    where: frontporch
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 80
