name: Bob (the Builder)
# One day Bob may want his brothers to help him with different base images, but today he's still handling all 3 alone

on:
  push:
    branches:    
      - release

jobs:
  Release_zendPHP_7-3:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'release') && contains(github.event.head_commit.message, '7.3') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build zendPHP 7.3
        run: |
            chmod a+x auto.sh
            ./auto.sh build 7.3

      - name: Test zendPHP 7.3
        run: ./auto.sh test 7.3

      - name: Push zendPHP 7.3
        run: docker login -u rbasayev -p ${{ secrets.DHUB_TOKEN }} && ./auto.sh push 7.3

  Release_zendPHP_7-4:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'release') && contains(github.event.head_commit.message, '7.4') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build zendPHP 7.4
        run: |
            chmod a+x auto.sh
            ./auto.sh build 7.4

      - name: Test zendPHP 7.4
        run: ./auto.sh test 7.4

      - name: Push zendPHP 7.4
        run: docker login -u rbasayev -p ${{ secrets.DHUB_TOKEN }} && ./auto.sh push 7.4

