name: Bob (the Builder)
# One day Bob may want his brothers to help him with different base images, but today he's still handling all 3 alone

on:
  push:
    branches:    
      - main

jobs:
  Release_zendPHP_7-4:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'release') && contains(github.event.head_commit.message, '7.4') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build zendPHP 7.4
        run: |
            chmod a+x auto.sh
            ./auto.sh build 7.4

      - name: Test zendPHP 7.4
        run: ./auto.sh test 7.4

      - name: Push zendPHP 7.4
        run: docker login -u rbasayev -p ${{ secrets.DHUB_TOKEN }} && ./auto.sh push 7.4

  Release_zendPHP_8-0:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'release') && contains(github.event.head_commit.message, '8.0') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build zendPHP 8.0
        run: |
            chmod a+x auto.sh
            ./auto.sh build 8.0

      - name: Test zendPHP 8.0
        run: ./auto.sh test 8.0

      - name: Push zendPHP 8.0
        run: docker login -u rbasayev -p ${{ secrets.DHUB_TOKEN }} && ./auto.sh push 8.0

  Release_zendPHP_8-1:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'release') && contains(github.event.head_commit.message, '8.1') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build zendPHP 8.1
        run: |
            chmod a+x auto.sh
            ./auto.sh build 8.1

      - name: Test zendPHP 8.1
        run: ./auto.sh test 8.1

      - name: Push zendPHP 8.1
        run: docker login -u rbasayev -p ${{ secrets.DHUB_TOKEN }} && ./auto.sh push 8.1

